### DISCUSSION TITLE
Add multiple keyboards

### DISCUSSION THREAD

**Discussion by xuantruongit32** [donniebreve/touchcursor-linux#69] [Q&A] [answered]
Please help me, how to add 2 keyboard in config file?

**Comment by Adda0** [comment]
Hello. Follow the instructions in `touchcursor.conf` to get the names for your keyboards. If you want to add more than one keyboard, simply add another line defining the name of the keyboard, like so:
```toml
[Device]
Name="Your First Keyboard"  # First keyboard: at home. 
Name="Your Second Keyboard"  # Second keyboard: at work, etc.
```

TouchCursor will look through all specified keyboard in the order they occur in the config file and once it finds one that exists, it will try to bind to that keyboard. Therefore, the order matters. In the example above, TouchCursor tries to find `Your First Keyboard` first, only it fails, it looks for the second one. Therefore, the first one has a sort of priority over the second one.
